blank_issues_enabled: false
contact_links:
  - name: 🔗 Quick Create new issue / 快速创建新 issue
    url: https://issue.xianniu-plus.org/
    about: The issue which is not created via https://issue.xianniu-plus.org/ will be closed immediately.
  - name: 🤔 Questions and Help / 问题和帮助
    url: https://github.com/xianniu-plus/xianniu-plus/discussions
    about: Ask questions and request help or other discussions.
